// eslint-disable-next-line import/no-anonymous-default-export
export default {
    GET_FAVORITES: "GET_FAVORITES",
    CHANGE_FAVORITES: "CHANGE_FAVORITES",
    LOGIN_USER:"LOGIN_USER",
    REGISTER_USER:"REGISTER_USER",
    LOGOUT_USER:"LOGOUT_USER",
    UPDATE_FAVORITES:"UPDATE_FAVORITES",
    LOGIN_USER_SESSIEN:"LOGIN_USER_SESSIEN",

};




